# Generated by Django 5.0.1 on 2024-01-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='replyingTo',
            new_name='commentAuthor',
        ),
    ]
